require('dotenv').config();
const { MODE, PORT, DB_NAME } = process.env;
require('./util/db');
const path = require('path');
const express = require('express');
const adminRoutes = require('./routes/admin');
const shopRoutes = require('./routes/shop');
const authRoutes = require('./routes/auth');
const User = require('./models/User');
const session = require('express-session');
const MongoDBStore = require('connect-mongodb-session')(session);

const app = express();

app.set('view engine', 'ejs');

app.use(express.urlencoded({ extended: false }));
app.use(express.static(path.join(__dirname, 'public')));

const store = new MongoDBStore({
  uri: `mongodb://localhost:27017/${DB_NAME}`,
  collection: 'sessions'
});

app.use(
  session({
    secret: 'my secret',
    resave: false,
    saveUninitialized: false,
    store
  })
);

const flash = require('connect-flash');
app.use(flash()); // NOTE: must register 'flash' middleware after initializing session

app.use(async (req, _, next) => {
  const { userId } = req.session;
  if (userId) {
    try {
      req.user = await User.findById(userId);
    } catch (err) {
      console.error('Error fetching user data for session:', err);
      return next(err);
    }
    req.loggedIn = true;
  } else {
    req.loggedIn = false;
  }
  next();
});

/* CSRF TOKEN
  • unique, random str generated by server & included in state-changing reqs
  • val embedded into forms as hidden input —> used to verify authenticity of reqs
*/
const csurf = require('csurf');
app.use(csurf());

app.use((req, res, next) => {
  // 'res.locals' —> local vars for lifetime of req (usually for passing data to views) **
  res.locals.loggedIn = req.loggedIn; // NOTE: 'req.loggedIn' removed from controller actions
  res.locals.csrfToken = req.csrfToken();
  next();
});

app.use('/admin', adminRoutes);
app.use(shopRoutes);
app.use(authRoutes);

app.use(({ name, message, stack }, req, res, _) => {
  res.status(500).render('error', {
    pageTitle: name,
    path: '',
    message,
    stack: MODE === 'development' ? stack : undefined
  });
});

app.listen(PORT, () => {
  console.log(`Server listening at PORT: ${PORT}`);
});
